# Generated by Django 5.1.1 on 2024-09-23 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sae',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sae_certificate_serial', models.BinaryField(blank=True, null=True)),
                ('kme_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UninitKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.BinaryField()),
                ('other_kme_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.BinaryField()),
                ('origin_sae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_keys', to='api.sae')),
                ('target_sae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_keys', to='api.sae')),
            ],
        ),
    ]
