# Generated by Django 5.1.1 on 2024-10-01 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMaterial',
            fields=[
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('encrypted_key', models.TextField()),
                ('iv', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KME',
            fields=[
                ('kme_id', models.UUIDField(default=uuid.UUID('a074a4bd-dd50-41f6-9db6-a03631e4f155'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('certificate', models.BinaryField(blank=True, null=True)),
                ('stored_key_count', models.IntegerField(default=0)),
                ('max_key_count', models.IntegerField(default=100000)),
                ('max_key_per_request', models.IntegerField(default=128)),
                ('max_key_size', models.IntegerField(default=1024)),
                ('min_key_size', models.IntegerField(default=64)),
                ('key_size', models.IntegerField(default=352)),
                ('max_SAE_ID_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KMEConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_certificate', models.BinaryField(blank=True, null=True)),
                ('source_kme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='api.kme')),
                ('target_kme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='api.kme')),
            ],
        ),
        migrations.CreateModel(
            name='SAE',
            fields=[
                ('sae_id', models.UUIDField(default=uuid.UUID('a4a204de-222c-4f97-b63f-067eca1eee05'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_master', models.BooleanField(default=False)),
                ('sae_certificate_serial', models.BinaryField(blank=True, null=True)),
                ('communicates_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sae')),
                ('kme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saes', to='api.kme')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=352)),
                ('origin_sae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_keys', to='api.sae')),
                ('target_saes', models.ManyToManyField(related_name='target_keys', to='api.sae')),
            ],
        ),
    ]
