# Generated by Django 5.1.1 on 2024-10-01 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kme',
            name='kme_id',
            field=models.UUIDField(default=uuid.UUID('8ab61c07-addc-48f4-8cf4-3e12922ef56d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sae',
            name='sae_id',
            field=models.UUIDField(default=uuid.UUID('ead581df-f7e1-49a1-880b-83b668273e22'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
