# Generated by Django 5.1.1 on 2024-10-01 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_kme_kme_id_alter_sae_sae_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kme',
            name='kme_id',
            field=models.UUIDField(default=uuid.UUID('0131d27d-f978-4591-add5-3e3679c0dcd0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sae',
            name='sae_id',
            field=models.UUIDField(default=uuid.UUID('24e12c2e-6875-41ae-9e0d-b12ff107bb08'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
