# Generated by Django 5.1.1 on 2024-10-01 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_kme_kme_id_alter_sae_sae_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kme',
            name='kme_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sae',
            name='sae_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
