# Generated by Django 5.1.1 on 2024-10-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_kme_kme_id_alter_sae_sae_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymaterial',
            name='consult_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consult_by', to='api.sae'),
        ),
    ]
