# Generated by Django 5.1.1 on 2024-10-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_keymaterial_consult_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymaterial',
            name='consult_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_by', to='api.sae'),
        ),
    ]
