# Generated by Django 5.1.1 on 2024-10-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_keymaterial_consult_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keymaterial',
            name='consult_by',
        ),
        migrations.AddField(
            model_name='keymaterial',
            name='consult_by',
            field=models.ManyToManyField(related_name='consulted_keys', to='api.sae'),
        ),
    ]
