# Generated by Django 5.1.1 on 2024-10-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_keymaterial_consult_by_keymaterial_consult_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymaterial',
            name='aes_key',
            field=models.TextField(default=b'n\xa0\xfb\xa90N5\x12)\xa3\x12.\xb0\xf1\x90?'),
        ),
    ]
